esphome:
  name: rename-me-please #Change this to whatever you named your device in ESPHome

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  password: "[CHANGE THIS BEFORE USE]" #This is mandatory for your device to recieve updates wirelessly

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: dht
    pin: GPIO4
    temperature:
      name: "RENAME ME Temperature" #The temperature sensor that shows up in Home Assistant
    humidity:
      name: "RENAME ME Humidity" #The humidity sensor that shows up in Home Assistant
    model: DHT22
     
  - platform: wifi_signal
    name: "Sean ESP32 01 WiFi Signal"
    update_interval: 60s
    
light:
  - platform: monochromatic
    name: "RENAME ME Built-in LED"
    output: builtin_led_output
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          update_interval: 2s
    
output:
  - id: builtin_led_output
    platform: ledc
    pin: GPIO2
