esphome:
  name: rename-me-please #Change this to whatever you named your device in ESPHome

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  password: "[CHANGE THIS BEFORE USE]" #This is mandatory for your device to recieve updates wirelessly

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: dht
    pin: GPIO4
    temperature:
      name: "RENAME ME Temperature" #The temperature sensor that shows up in Home Assistant
    humidity:
      name: "RENAME ME Humidity" #The humidity sensor that shows up in Home Assistant
    model: DHT22